# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finalSTT.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtWidgets import QFileDialog


class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1013, 667)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(255)
        sizePolicy.setVerticalStretch(255)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(508, 339))
        MainWindow.setStyleSheet("background-image: url(:/imgs/images/mainWindow.jpg);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 30, 481, 471))
        self.textBrowser.setMouseTracking(True)
        self.textBrowser.setWhatsThis("")
        self.textBrowser.setStyleSheet("border-image: url(:/imgs/images/blackboard.jpg) 0 0 0 0 stretch stretch;")
        self.textBrowser.setUndoRedoEnabled(True)
        self.textBrowser.setObjectName("textBrowser")
        self.start_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.start_pushButton.setGeometry(QtCore.QRect(710, 600, 101, 28))
        palette = QtGui.QPalette()
        self.start_pushButton.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setBold(False)
        font.setWeight(50)
        self.start_pushButton.setFont(font)
        self.start_pushButton.setMouseTracking(True)
        self.start_pushButton.setAutoFillBackground(False)
        self.start_pushButton.setStyleSheet("border-image: url(:/imgs/images/white.webp);")
        self.start_pushButton.setAutoDefault(False)
        self.start_pushButton.setDefault(False)
        self.start_pushButton.setFlat(False)
        self.start_pushButton.setObjectName("start_pushButton")
        self.micStart = QtWidgets.QLabel(self.centralwidget)
        self.micStart.setGeometry(QtCore.QRect(710, 520, 101, 71))
        self.micStart.setMouseTracking(False)
        self.micStart.setStyleSheet("border-image: url(:/imgs/images/textBack.jpg) 0 0 0 0 stretch stretch;")
        self.micStart.setText("")
        self.micStart.setPixmap(QtGui.QPixmap(":/imgs/images/micStop.png"))
        self.micStart.setScaledContents(True)
        self.micStart.setObjectName("micStart")
        self.audioAttatch = QtWidgets.QLabel(self.centralwidget)
        self.audioAttatch.setGeometry(QtCore.QRect(860, 520, 91, 71))
        self.audioAttatch.setAcceptDrops(False)
        self.audioAttatch.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.audioAttatch.setStyleSheet("border-image: url(:/imgs/images/textBack.jpg) 0 0 0 0 stretch stretch;")
        self.audioAttatch.setFrameShadow(QtWidgets.QFrame.Plain)
        self.audioAttatch.setText("")
        self.audioAttatch.setPixmap(QtGui.QPixmap(":/imgs/images/audioFile.png"))
        self.audioAttatch.setScaledContents(True)
        self.audioAttatch.setAlignment(QtCore.Qt.AlignCenter)
        self.audioAttatch.setWordWrap(True)
        self.audioAttatch.setObjectName("audioAttatch")
        self.audioAttatch_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.audioAttatch_pushButton.setGeometry(QtCore.QRect(860, 600, 101, 28))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.audioAttatch_pushButton.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setBold(False)
        font.setWeight(50)
        self.audioAttatch_pushButton.setFont(font)
        self.audioAttatch_pushButton.setMouseTracking(True)
        self.audioAttatch_pushButton.setAutoFillBackground(False)
        self.audioAttatch_pushButton.setStyleSheet("border-image: url(:/imgs/images/white.webp) 0 0 0 0 stretch stretch;")
        self.audioAttatch_pushButton.setAutoDefault(False)
        self.audioAttatch_pushButton.setDefault(False)
        self.audioAttatch_pushButton.setFlat(False)
        self.audioAttatch_pushButton.setObjectName("audioAttatch_pushButton")
        self.stop_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.stop_pushButton.setGeometry(QtCore.QRect(710, 630, 101, 28))
        palette = QtGui.QPalette()
        self.stop_pushButton.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setBold(False)
        font.setWeight(50)
        self.stop_pushButton.setFont(font)
        self.stop_pushButton.setMouseTracking(True)
        self.stop_pushButton.setAutoFillBackground(False)
        self.stop_pushButton.setStyleSheet("border-image: url(:/imgs/images/white.webp) 0 0 0 0 stretch stretch;")
        self.stop_pushButton.setAutoDefault(False)
        self.stop_pushButton.setDefault(False)
        self.stop_pushButton.setFlat(False)
        self.stop_pushButton.setObjectName("stop_pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(530, 30, 451, 471))
        self.label.setStyleSheet("border-image: url(:/imgs/images/spectrogram.png) 0 0 0 0 stretch stretch;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 520, 671, 141))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-image: url(:/imgs/images/textBack.jpg) 0 0 0 0 stretch stretch;")
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.start_pushButton.raise_()
        self.micStart.raise_()
        self.audioAttatch.raise_()
        self.textBrowser.raise_()
        self.audioAttatch_pushButton.raise_()
        self.stop_pushButton.raise_()
        self.label.raise_()
        self.label_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        ### editing here###
        # QtGui.__init__(self)
        # self.ui=Ui_MainWindow()
        # self.ui.setupUi(self)
        #############################


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.start_pushButton.clicked.connect(self.show_micStart)
        self.stop_pushButton.clicked.connect(self.show_micStop)

        self.audioAttatch_pushButton.clicked.connect(self.open) # connect clicked to self.open()
        # self.show()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Speech to Text"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#ffffff;\">Output will be displayed here...</span></p></body></html>"))
        self.start_pushButton.setText(_translate("MainWindow", "Start"))
        self.audioAttatch_pushButton.setText(_translate("MainWindow", "Attatch here"))
        self.stop_pushButton.setText(_translate("MainWindow", "Stop"))
        self.label_2.setText(_translate("MainWindow", "Hey there! \n"
"Hope you\'re having a good day :) \n"
" \n"
"I can convert your speech to text.  \n"
"There are 2 ways. One through \"mic\" and other by \"attaching your audio file.\""))


    def show_micStart(self):
        self.micStart.setPixmap(QtGui.QPixmap(":/imgs/images/micStart.png"))

    def show_micStop(self):
        self.micStart.setPixmap(QtGui.QPixmap(":/imgs/images/micStop.png"))

    def open(self):
        path = QFileDialog.getOpenFileName(self, 'Open a file', '',
                                        'All Files (*.*)')
        if path != ('', ''):
            print("File path : "+ path[0])
        

import resFile_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
